
name: CI

on:
  push

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn
      - name: yarn build
        run: yarn build
      - name: yarn lint
        run: yarn lint
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Webpack build
          path: dist
        env:
          CI: true