version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: jefke
      POSTGRES_DB: csmm-payments