name: docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [store]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: catalysmsservermanager
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/catalysmsservermanager/frontend-${{ matrix.package }}:latest
          build-args: |
            "package_name=${{ matrix.package }}"
            "REACT_APP_API=https://api.store.csmm.fun/api"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
